# Generated by Django 3.1.10 on 2021-05-12 16:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0002_auto_20210512_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='steam_field_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
