# Generated by Django 3.1.8 on 2021-05-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('simple_page', '0003_simplepage_steam_field_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='test_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
