# Generated by Django 3.1.8 on 2021-05-13 12:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0004_simplepage_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='image_block',
            field=wagtail.core.fields.StreamField([('image_block', wagtail.core.blocks.StreamBlock([]))], blank=True),
        ),
    ]
