# Generated by Django 3.1.8 on 2021-05-13 12:40

from django.db import migrations
import simple_page.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0006_auto_20210513_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='image_block',
            field=wagtail.core.fields.StreamField([('image_block', wagtail.core.blocks.StructBlock([('image', simple_page.blocks.CustomImageChooserBlock())]))], blank=True),
        ),
    ]
