# Generated by Django 3.1.8 on 2021-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0007_auto_20210513_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplepage',
            old_name='image_block',
            new_name='super_image_block',
        ),
    ]
