# Generated by Django 3.1.8 on 2021-05-13 13:37

from django.db import migrations
import simple_page.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0008_auto_20210513_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='steam_field_content',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='super_image_block',
        ),
        migrations.RemoveField(
            model_name='simplepage',
            name='test_image',
        ),
        migrations.AddField(
            model_name='simplepage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('sub_heading', wagtail.core.blocks.CharBlock(form_classname='Sub-Heading')), ('paragraph', wagtail.core.blocks.CharBlock()), ('image_card', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(max=1024)), ('image', simple_page.blocks.CustomImageChooserBlock())]))], blank=True),
        ),
    ]
