version: '3.7'

services:
  web:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000 --settings=app.settings.dev
    # volumes:
    #   - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./local_env_files/.env.dev

    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./local_env_files/.env.dev.db

volumes:
    postgres_data: