# Generated by Django 3.1.8 on 2021-04-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='name',
            new_name='serviceName',
        ),
    ]
