# Generated by Django 3.1.8 on 2021-04-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210421_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='maxAge',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='minAge',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='serviceName',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='url',
        ),
    ]
