# Generated by Django 3.1.8 on 2021-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicepage_servicename'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
