# Generated by Django 3.1.8 on 2021-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_servicepage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='serviceName',
            new_name='name',
        ),
    ]
