# Generated by Django 3.1.8 on 2021-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210421_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
