# Generated by Django 3.1.8 on 2021-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210421_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='serviceUrl',
            field=models.URLField(),
        ),
    ]
