# Generated by Django 3.1.8 on 2021-04-21 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('service', '0010_auto_20210421_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='Service',
        ),
    ]
