# Generated by Django 3.1.8 on 2021-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20210421_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supportType',
            field=models.CharField(default='', max_length=100, unique=False),
            preserve_default=False,
        ),
    ]
