# Generated by Django 3.1.8 on 2021-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_service_supporttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='supportType',
            field=models.CharField(max_length=100),
        ),
    ]
